# VARIABLES
@baseUrl = http://localhost:3333

# Health chech
# @name healthCheck
GET {{baseUrl}}/health

###

# GET rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
# É preciso enviar o Content-Type, pois é preciso informar a forma de como
# está sendo enviado do dados para o Backend
Content-Type: application/json

{
    "name": "Sala de teste2",
    "description": "Essa é uma sala de teste."
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
# 6b70810c-74ff-4ce9-2665-dbe392f0610b
# {{roomId}}
POST {{baseUrl}}/rooms/6b70810c-74ff-4ce9-2665-dbe392f0610b/questions
Content-Type: application/json

{
    "question": "O que é React?"
}